services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  goose-migrations:
    image: kukymbr/goose-docker:3.24.2
    container_name: migrator
    command: up
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres port=5432 user=${PG_USER:-postgres} password=${PG_PASSWORD} dbname=${PG_NAME}
      - GOOSE_MIGRATION_DIR=./migrations
    healthcheck:
      test: ["CMD", "sh", "-c", "exit 0"]
      interval: 5s
      timeout: 3s
      retries: 1
    volumes:
      - ./migrations:/migrations

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    depends_on:
      postgres:
        condition: service_healthy
      goose-migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_NAME=${PG_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MESSAGE_TTL=${MESSAGE_TTL}
      - LOG_FILE=${LOG_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./assets:/app/assets

volumes:
  postgres_data: